### ISSUE TITLE
be able to provide own contexts

### ISSUE THREAD

**Issue by poteto** [dockyard/ember-in-viewport#10]
For example, this could be useful when you want the context to be something other than a window, e.g. a container div.

**Comment by samselikoff** [comment]
Did #13 really close this? It seems like `window` is still hard-coded [here](https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L67).

Happy to PR this if you agree.

(Thanks for this awesome addon!)

**Comment by poteto** [comment]
Good catch, you're right the hardcoded `window` should be removed
