### ISSUE TITLE
Trigger when entering/exiting

### ISSUE THREAD

**Issue by oligriffiths** [DockYard/ember-in-viewport#101]
Hi

Would it be possible to allow for triggering `isEntering()`, `isExiting()` hooks for when the element is 1px in or out of the viewport. I'm using this to do lazy image loading and I want to start loading the image as soon as 1px of it enters the viewport, however currently the hook doesn't fire until the while image is within the viewport.

Oli

**Comment by backspace** [comment]
Would the `viewportTolerance` option work for that?

**Comment by shankarsridhar** [comment]
@oligriffiths You can use the `viewportTolerance.bottom` option for you use case.
For example, if u wanna do it in your components, you can use the following snippet,

```
didInsertElement() {
  this._super(...arguments);
  Ember.run.scheduleOnce('afterRender', this, () => {
    set(this, 'viewportTolerance.bottom', this.$().height());
  });
},
```

I am using the above snippet in my ember app to lazy compute and render components rendering charts. works just fine.

Good luck!

**Comment by snewcomer** [comment]
Intersection Observer is on master!  So `threshold` is the relevant field in the IntersectionObserver API.  `intersectionThreshold` is one of the properties you can set on the mixin - 0 through 1.  1 meaning every pixel of the target must be visible.

Lmk if there is still some requirements missing.
