### ISSUE TITLE
didScroll event for elements exiting the viewport.

### ISSUE THREAD

**Issue by totanus** [DockYard/ember-in-viewport#104]
Feature request: didScroll event for elements LEAVING the viewport.

Example
```
didScrollExiting(direction) {
    console.log(direction); // 'up' || 'down' || 'left' || 'right'
  }
```

**Comment by snewcomer** [comment]
@totanus IntersectionObserver is on master!  The method I think you are looking for is `didExitViewport`.  Here is the relevant [line](https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L146).  The scroll direction is [here](https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L166) as well.

Lmk if you have any other concerns.
