### ISSUE TITLE
Consider refactor using IntersectionObserver API

### ISSUE THREAD

**Issue by bcardarella** [DockYard/ember-in-viewport#106]
rAF was a good stop gap over the more costly polling solution to enable smoother scrolling events, but even it has its limits perf wise. With ItnersectionObserver heading towards acceptance it could be a better long-term solution and ember-in-viewport should consider this the preferred method.

I would advocate for detecting the IntersectionObserver API, if it is available use it. If not fall back to the existing method of rAF, then more legacy Web APIs

Notes: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
Example: https://codepen.io/SimonEvans/pen/Qqjxde

**Comment by rwjblue** [comment]
FWIW, there is an addon that we use in LI that leverage an `IntersectionObserver` polyfill. Unsure if it helps here or is completely unrelated (sorry if off topic).

Repos:

* https://github.com/linkedin/spaniel
* https://github.com/asakusuma/ember-spaniel
