### ISSUE TITLE
Demo link is dead

### ISSUE THREAD

**Issue by hybridmuse** [DockYard/ember-in-viewport#115]
Link is dead: http://development.ember-in-viewport-demo.divshot.io/

**Comment by cibernox** [comment]
Yeah, 👍 . This needs a new deploy.

**Comment by sheriffderek** [comment]
If divshot has merged into firebase, [surge.sh](http://surge.sh/) may be a solid option for demo sites (that don't require fastboot). https://github.com/kiwiupover/ember-cli-surge

**Comment by fusion2004** [comment]
[Netlify](https://www.netlify.com/) is a good option, too.
