### ISSUE TITLE
Use #ember-testing-container as a context when testing

### ISSUE THREAD

**Issue by bobisjan** [DockYard/ember-in-viewport#116]
Hi,

when updating to Ember 2.17 our tests start failing due to invalid `didEnterViewport` events - component with `InViewport` mixin was in `window` viewport, but was outside the `#ember-testing-container` viewport.

It seems that `InViewport` mixin should use `#ember-testing-container` when testing as a context instead of `window` here

- https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L67,
- https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L69,
- https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L225.

`isInViewport` detection should be also changed accordingly

- https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L98.

Happy to work on this if this makes sense.

Thanks

**Comment by snewcomer** [comment]
@bobisjan Did if fail b/c it didn't properly scroll the page?  What version of Ember were you upgrading from?

**Comment by snewcomer** [comment]
@bobisjan There is also this issue #95.

Also PR #113 may fix this issue.

**Comment by bobisjan** [comment]
> What version of Ember were you upgrading from?

Our application is running on Ember 2.16.

> There is also this issue #95.

Not sure if it's related, I had the opposite problem - `didEnterViewport` was fired when it should not.

> Did if fail b/c it didn't properly scroll the page?

After making change 2., it scrolls correctly in `#ember-testing-container`.

<hr>

The changes I made locally to pass tests:

1. Update code in `InViewport` mixin to use `#ember-testing-container`,
2. Update logic in our `scrollToElement` test helper to scroll in `#ember-testing-container` (not in `window` itself).
3. Update logic to reset scroll position in `#ember-testing-container` (not in `window` itself) after each affected test.

> Also PR #113 may fix this issue.

Will try #113, thanks.

**Comment by snewcomer** [comment]
@bobisjan See the line below for an example of scrolling an element into view if it helps you.

https://github.com/DockYard/ember-in-viewport/pull/113/files#diff-919b4e42a185a63ca7395afa766d8502R17

We should probably add some documentation on testing as well to the README as wel.

**Comment by bobisjan** [comment]
@snewcomer, I've run tests against your branch, quick summary:

1. tests passed ✅ with `viewportUseIntersectionObserver = true`,
2. tests failed ⛔️ with `viewportUseIntersectionObserver = false`.

I'm not sure how 1. can pass, because observer has `root = null`, so it should use whole viewport (not `#ember-testing-container`s viewport) and I would expect that it fails the same way, but I'm missing something 🤔.

Without observer (2.) it has same problem like I mentioned before (`didEnterViewport` is fired when it should not). I've tried to change `scrollableArea` to `#ember-testing-container`, but then `didEnterViewport` is not fired when it should. I'm not sure if it's OK to compare values from `element.getBoundingClientRect()` with different context other than `window` in `isInViewport`.

**Comment by bobisjan** [comment]
@snewcomer, [here](https://github.com/snewcomer/ember-in-viewport/compare/intersection-observer...bobisjan:testing-context) are changes I made based on your `intersection-observer` branch to make our tests to pass with `viewportUseIntersectionObserver = false`.

**Comment by snewcomer** [comment]
@bobisjan Cool!  So a few things of note:

1.  I may have not thought of all the scenarios, but generally you will want the library to choose which method to use (IntersectionObserver, rAF, or scroll events).  And IntersectionObserver is, in most all cases, the one you want to use and the default in that PR.  The perf improvements are significant so setting `viewportUseIntersectionObserver = false`, although an option, may not be what you want to do (be open to understanding your perspective! :+1:).

2.  In a testing scenario, if you are using a modern browser / headless Chrome/Firefox, the library will use the default and will support IntersectionObserver.  The case where this falls down is if you are testing with IE, then it will fallback to rAF.

**Comment by rwjblue** [comment]
@bobisjan - Would you mind reviewing the changes made in https://github.com/ember-cli/ember-cli/pull/7507 and apply them to your app? There was a bug in the blueprints of ember-cli <= 2.17.1 which caused component tests to be scoped to the wrong root element (they would be appended to `body` instead of `#ember-testing`).  I'm definitely not certain this is the issue you are running into, but I wanted to point out that fix and see if you could double check...

**Comment by bobisjan** [comment]
Thanks @rwjblue,

with `ember-cli@2.17.1` and changes from [ember-cli/ember-cli#7507](https://github.com/ember-cli/ember-cli/pull/7507) our tests pass ✅ with  `ember-in-viewmport@2.1.1` (current) and also with @snewcomer's `interesection-observer` branch 🎊.

So, I think that this issue can be closed ☺️.

**Comment by bobisjan** [comment]
@snewcomer, I totally agree that add-on should use the best method available in a browser and automatically fall down 👍. I've used `viewportUseIntersectionObserver = false` to ensure that tests pass in both scenarios.

Definitely I look forward to your PR to be merged and released 😍.

**Comment by rwjblue** [comment]
Awesome, thank you for confirming @bobisjan, and I’m sorry for that specific bug :(

We’ll try to get 2.17.2 out soon to hopefully prevent others from hitting it...

**Comment by snewcomer** [comment]
@bobisjan great hunting everybody!  Glad it was resolved :sweat_smile:
