### ISSUE TITLE
Change in viewport without scroll don't trigger didEnterViewport

### ISSUE THREAD

**Issue by arturalkaim** [DockYard/ember-in-viewport#120]
## Version
**2.1.1**

## Test Case
I have a list with images that are loaded when they are on the viewport. 
When I scroll the images are loaded as expected.

## Expected Behavior
I have now a set of filters that filter the images in the list. When I change the filter I expect that the images that were hidden and now are in the viewport to be loaded.

## Actual Behavior
The element that are now on the viewport never trigger `didEnterViewport`. If I scroll a bit they are immediately loaded.

**Comment by snewcomer** [comment]
@arturalkaim Thanks for reporting the issue!  This may have something to do with some boolean logic in the mixin.  Would you mind trying one thing out for me?  Could you test out this PR's [branch](https://github.com/DockYard/ember-in-viewport/pull/113)?

`"ember-in-viewport": "git+ssh://git@github.com:snewcomer/ember-in-viewport.git#intersection-observer"`

And let us know what the effect is?  If it works, then I think we may have some logic to cleanup once that PR lands in master.

**Comment by arturalkaim** [comment]
Thanks @snewcomer,  I can test that in a bit. 

To workaround this issue I'm calling `Ember.$(window).scroll();` whenever I do any filtering.

**Comment by snewcomer** [comment]
@arturalkaim Could you try out 2.1.2 and see if anything has changed for you?

**Comment by snewcomer** [comment]
@arturalkaim Will close for now.  Lmk if `3.0.1` helps and feel free to open again.
