### ISSUE TITLE
Error: Could not find module `@ember/polyfills` imported from `myapp/initializers/viewport-config`

### ISSUE THREAD

**Issue by teakap** [DockYard/ember-in-viewport#124]
I get the error in the browser console as soon as the server runs. 
I am using: 
`ember-in-viewport: ^2.1.1`
`ember-cli: ^2.12.3`

I've cleaned node and bower modules a couple of times, but the issue remains. Any ideas?

**Comment by snewcomer** [comment]
@teakap Ah thank you for bringing our attention to this!  The new ember imports `@ember/...` is only safe if it is in the `addon` folder.  I think the instance-initializer essentially needs to be in the addon folder and re-exported in the `app` folder.  Let me create an issue for it.

**Comment by snewcomer** [comment]
@teakap Would you mind trying out `ember-in-viewport: "DockYard/ember-in-viewport"` (master branch) in your package.json and lmk if the PR fixed it?  We will release `2.2.1` if so.  Thanks again!

**Comment by teakap** [comment]
@snewcomer I can confirm! No console errors, and the expected behavior is the actual behavior :)
