### ISSUE TITLE
didExitViewport not firing on Ember 3.1 beta?

### ISSUE THREAD

**Issue by lougreenwood** [DockYard/ember-in-viewport#139]
## Version
3.0

ember-cli: 3.1.0-beta.1
node: 9.10.1
os: darwin x64

## Steps to reproduce
Scroll the page 

## Expected Behavior
Scrolling an element out of view should trigger the `didExitViewport`

## Actual Behavior
`didExitViewport` is not fireside when scrolling an element out of view.
`didEnterViewport` is only fired once when scrolling into view.

**Comment by snewcomer** [comment]
@lougreenwood Hi 👋  I'm wondering what your exact scenario may be.  A few questions:

1.  Is this on Chrome?  Same behavior on Firefox as well?
2.  Is your scrollable area the window?
3.  What are some of the config options you pass?

Also, I put some notes on the `intersectionThreshold`, so curious if any applies to you.  Look forward to hearing back!

**Comment by snewcomer** [comment]
@lougreenwood Let me know if you are still having the problem.  3.0.2 is upgraded to Ember 3.1.  Closing for now but feel free to open again if you still are seeing an issue!

![did_exit_viewport](https://user-images.githubusercontent.com/7374640/38790690-be6fa0a0-40f7-11e8-93d7-60c774db3e8f.gif)
