### ISSUE TITLE
viewportEnabled is undefined in addon integration tests 

### ISSUE THREAD

**Issue by mkay581** [DockYard/ember-in-viewport#142]
## Version
2.1.1 (I've also tried this on latest version and still same behavior)

## Test Case
[`viewportEnabled` is `undefined`](https://github.com/DockYard/ember-in-viewport/blob/v2.2.1/addon/mixins/in-viewport.js#L49) when testing this package mixed into a component (inside of an addon) during integration testing. It also appears none of the [default configs](https://github.com/DockYard/ember-in-viewport/blob/v2.2.1/addon/initializers/viewport-config.js#L4) get added.

## Steps to reproduce
Set a debugger statement/breakpoint inside [`didInsertElement()` hook in-viewport.js file where `viewportEnabled` is evaluated](https://github.com/DockYard/ember-in-viewport/blob/v2.2.1/addon/mixins/in-viewport.js#L49).

## Expected Behavior
`viewportEnabled` should be `true` 

## Actual Behavior
`viewportEnabled` is `undefined`

**Comment by snewcomer** [comment]
@mkay581 I haven't been able to reproduce.  I still need to add more tests to this PR to upgrade `ember-light-table`, but seems `viewportEnabled` is true on my end.  If you had a screenshot to reproduce, that would help! 

https://github.com/offirgolan/ember-light-table/pull/548

**Comment by snewcomer** [comment]
Closing for now.  Talked with @mkay581 and the latest versions of this addon fix the issue.
