### ISSUE TITLE
BUG: viewportUseIntersectionObserver : true in config throw error in Safari

### ISSUE THREAD

**Issue by kiwiupover** [DockYard/ember-in-viewport#146]
## Version
3.0.3

## Steps to reproduce
ADD `viewportUseIntersectionObserver : true` to the viewportConfig object

## Expected Behavior
I would expect that if the IntersectionObserver in NOT support by the browser `ember-in-viewport` would fall back to rAF

## Actual Behavior
Throws an error `Can't find variable: IntersectionObserver`

**Comment by snewcomer** [comment]
@kiwiupover Hey!  I think we may need to update the docs.  That is what it currently does - it's [fallback](https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L59) is to rAF if it does not support IntersectionObserver.  

I don't think there is any reason one would want to hardcode it `true` in your component's config (that is why I think I need to update the docs as it is misleading).  I think we want to only allow setting it to `false`.

What do you think?

**Comment by kiwiupover** [comment]
@snewcomer I agree the docs is the right place todo update this. 

Do you have a use case where you would not want `IntersectionObserver` ?

**Comment by kiwiupover** [comment]
Here is a use case from our code. 
```js
import StickyElementTrigger from 'ember-sticky-element/components/sticky-element/trigger';

export default StickyElementTrigger.extend({
  init() {
    this._super(...arguments);

    let isIE = false;
    if (window && window.navigator && window.navigator.userAgent) {
      isIE = /msie\s|trident\/|edge\//i.test(window.navigator.userAgent);
    }

    if (isIE) {
      this.set('viewportUseRAF', true);
      this.set('viewportUseIntersectionObserver', false);
    }
  }
});
```

**Comment by kiwiupover** [comment]
I will update the docs

**Comment by snewcomer** [comment]
@kiwiupover Thanks! Yeah I haven't come across a need to _not_ use IntersectionObserver.  Sometime in the future, we will have a good polyfill and eventually we will just rely on IntersectionObserver.  So would love to hear about a good use case.  So for now, we have the can-use-intersection-observer, which checks for 'IntersectionObserver' in window.

https://github.com/DockYard/ember-in-viewport/blob/master/addon/utils/can-use-intersection-observer.js

**Comment by snewcomer** [comment]
@kiwiupover I got some time today if you would like me to update the docs

**Comment by snewcomer** [comment]
@kiwiupover I put something up real quick #147.  Lmk what you think.
