### ISSUE TITLE
Attempting to register an unknown factory: `config:in-viewport`

### ISSUE THREAD

**Issue by fsmanuel** [dockyard/ember-in-viewport#15]
Using `ember-lazy-image` I now get this error.
When I add `viewportConfig` to the `environment.js` it is gone.

To fix that we should add a fallback:
```
// app/initializers/viewport-config.js
application.register('config:in-viewport', viewportConfig || {}, { instantiate: false });
```
I tried `const { viewportConfig } = config || {};` but that didn't worked so I did `viewportConfig || {}`

**Comment by poteto** [comment]
Yeah that's a good catch, I'll issue a bugfix. Thanks!

**Comment by fsmanuel** [comment]
I learn so much es6 features by reading your code!
