### ISSUE TITLE
Scrollable area width not calculated correctly in _setViewportEntered()

### ISSUE THREAD

**Issue by pfgilbert** [DockYard/ember-in-viewport#165]
In the non-Observer case, if a `scrollableArea` is provided, the `_setViewportEntered()` method in addon/mixins/in-viewport.js appears to calculate the width of that area incorrectly.  

What's in the code:
```
    const height = scrollableArea ? scrollableArea.offsetHeight + scrollableArea.getBoundingClientRect().top : window.innerHeight;
    const width = scrollableArea ? scrollableArea.offsetWidth : window.innerWidth;
```

What I think it should be:
```
    const height = scrollableArea ? scrollableArea.offsetHeight + scrollableArea.getBoundingClientRect().top : window.innerHeight;
    const width = scrollableArea ? scrollableArea.offsetWidth + scrollableArea.getBoundingClientRect().left : window.innerWidth;
```
Was this done intentionally?  I can try to come up with a simple test case that demonstrates why/how it's a problem, but to me this just looks like an obvious oversight.

## Version
3.0.3

## Test Case
Will provide if others agree this is a bug

**Comment by pfgilbert** [comment]
@snewcomer It looks like this is came in when the height calculation was updated in this commit: https://github.com/DockYard/ember-in-viewport/commit/4a11b4e70dd388b444c1e8fe0d1a7e4860df6700#diff-2c2e18a7ca7e78c5dad2dd4b0e42d657

**Comment by snewcomer** [comment]
@pfgilbert 💯 I think what you found is a bug.  I have a bug w/ right-left scrolling and this may help so thank you!  

Lmk if you have time to put up a PR.  Otherwise I can get to it sometime later this week.
