### ISSUE TITLE
viewportspy sets viewportEntered to false (permanently)

### ISSUE THREAD

**Issue by mcfiredrill** [DockYard/ember-in-viewport#181]
The docs for viewportSpy state:
`When false, the Mixin will only watch the Component until it enters the viewport once, and then it sets viewportEntered to true (permanently),`
However, it seems that it sets viewportEntered to `false` ? https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L305

Is this behavior incorrect, or are the docs wrong?

## Version
3.3.0

**Comment by snewcomer** [comment]
@mcfiredrill It will only stop if `viewportSpy: false`, which is the default.  Do you think the docs could be improved?  If so, feel free to submit a PR!  THanks!

https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L121

**Comment by snewcomer** [comment]
Closing for now.  Feel free to submit a PR to the docs or lmk if you have other questions!
