### ISSUE TITLE
3.5.0 `inViewport` injection causes incompatibility with ember-light-table

### ISSUE THREAD

**Issue by kevinansfield** [DockYard/ember-in-viewport#186]
There was an unintentional breaking change that turned up in 3.5.0, at least for its usage in `ember-light-table`.

In `ember-light-table`, the component which extends from the InViewportMixin has a [closure action called `inViewport`](https://github.com/offirgolan/ember-light-table/blob/69fe819d9bf404c0bfed8a32c197d61176f4f678/addon/templates/components/lt-body.hbs#L61) which clobbers the recently introduced [`inViewport` injection](https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L34).

The result is a `Ember.get(...).setupIntersectionObserver is not a function` error which is thrown from the [mixin here](https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L135).

**Comment by snewcomer** [comment]
😢

**Comment by snewcomer** [comment]
@kevinansfield Perhaps rename the service injection?  `inViewportService: inject('in-viewport')` or something like that?

**Comment by snewcomer** [comment]
Hi @kevinansfield 👋 Anymore thoughts?

**Comment by fran-worley** [comment]
@snewcomer I think this might require a change in ember light table as I've just tried bumping the ember-in-viewport version addon dependency (even as low as v3.0.4) and am getting this and other similar errors...

**Comment by snewcomer** [comment]
@fran-worley Yeah I think you are right.  The first step involves bumping the deps and travis config only back until 2.16.  Then I think we can go from there.

https://github.com/offirgolan/ember-light-table/pull/682

**Comment by fran-worley** [comment]
@snewcomer see https://github.com/offirgolan/ember-light-table/pull/693 for the version bump and fix. I can't see a way around the API change for ember light table as mirroring the service name really can't be a good idea!

**Comment by fran-worley** [comment]
@kevinansfield this is being fixed in ember-light-table #693 which will hopefully be released as v2.0.0.beta.4 once we've finished it! I suspect that this issue can then be closed as it's ELT and not ember-in-viewport at fault here.
