### ISSUE TITLE
Viewport tolerance detection fails on scrollable elements in iOS webkit and Mac Safari

### ISSUE THREAD

**Issue by edeis53** [DockYard/ember-in-viewport#202]
## Version

"ember-in-viewport": "^3.5.8",
"ember-cli": "~3.7.1",

## Test Case

Full test case.
https://github.com/edeis53/inviewport-ios-issue

## Steps to reproduce

Clone the repo. Then `ember server` and test on an actual iOS device. I was using iPad.

Visit the following routes via the links in the app and try scrolling:
`horizontal-scroll within an element`
`vertical-scroll within an element`

## Expected Behavior

When using tolerance for in-viewport, an element outside the viewport should be detected within foresaid tolerance amount.

## Actual Behavior

When the scrollableArea is an element, child elements are only detected when absolutely in-viewport instead of within the tolerance amount. This issue only effects certain browsers/os.

When the scrollableArea is null (which defaults to window) viewport tolerance detection works for all browsers.

## Effected Browsers that fail for tolerance detection if the scrollableArea is a DIV.
iOS
Chrome: FAILS (75.0.3770.70)
Safari: FAILS (iOS 12.3.1)

MacOS Desktop
Safari: FAILS (Version 12.1.1 (14607.2.6.1.1)
Safari Technology Preview: FAILS Release 84 (Safari 13.0, WebKit 14608.1.25.2)
Chrome: Works :) (Version 74.0.3729.169)

Only Chrome Mac Desktop will detect with tolerance on a scrollable element.

**Comment by edeis53** [comment]
Also tested the demo against android chrome. Works in all scenarios.

Android
Chrome: Works! :) Version 74.0.3729.157

**Comment by edeis53** [comment]
You can also reproduce this error using ember-in-viewports dummy app.

Use the `Infinity Right Left` demo.

Set the tolerance to 500 or so.
```
    this.viewportToleranceOverride = {
      right: 500
    };
```

Load up Safari on MacOS Desktop.
-Scroll to the end of the frame, the infinity load items will only load when you reach the end of the scroll.

Load up Chrome on MacOS Desktop
-Try scrolling to the end of the frame, the inifinity load items will at the tolerance threshold.

**Comment by snewcomer** [comment]
@edeis53 Amazing reproduction!  I have noticed the same thing but haven't looked into it too much.  I assumed it was due to differing implementations of the spec.  What do you think?

**Comment by edeis53** [comment]
@snewcomer I haven't had any experience with the spec or api for intersection observer before. So I just build out a new demo page in my repo that uses just pure intersection observer. Yes, it seems it's an issue at webkit's end. I opened a bug here: https://bugs.webkit.org/show_bug.cgi?id=198784 please add anything you think might help in getting the ticket notice and solved.

**Comment by edeis53** [comment]
My ticket is now patched and working in Safari Technical Preview. Should be pushed to production iOS in version 13 or so.
