### ISSUE TITLE
Memory leak: Related to WeakMap?

### ISSUE THREAD

**Issue by allthesignals** [DockYard/ember-in-viewport#203]
![image](https://user-images.githubusercontent.com/5004319/61248971-26037c00-a722-11e9-9df6-e225d708ee3f.png)

I've been working on memory snapshots for my app, and this is one that consistently appears leftover after running a test. The relevant lines that appear in the snapshot are [here](https://github.com/DockYard/ember-in-viewport/blob/024d41afde79b6d1b3e08324a11004c4b4412507/addon/services/in-viewport.js#L26) and [here](https://github.com/DockYard/ember-in-viewport/blob/024d41afde79b6d1b3e08324a11004c4b4412507/addon/services/in-viewport.js#L169-L173).

Maybe I'm misinterpreting something? I'm running `"ember-in-viewport": "3.5.8",` of this adodon, ember-source is 3.10.

Thanks!

**Comment by allthesignals** [comment]
This seems relevant, maybe I am misinterpreting: https://discuss.emberjs.com/t/datadown-to-a-component-leads-to-memory-leak/14649/5?u=wmattgardner

**Comment by snewcomer** [comment]
@allthesignals Interesting!  My understanding was similar.  If the path to the key or the weak map itself was dropped, the value will be gc'ed.  But what you are showing me is either 

1. the `destroy` method isn't being called on the service and de-referencing the `registry` on the service
2. the `destroy` method is being called, but somehow Ember/the service is still retaining some path to the WeakMap.

Assuming the `destroy` method is called between test runs, one option is to set the `registry` as a global in that module and reference it to null on destroy.  Something could be retaining onto that property through Ember's `set` logic.

Would it be possible to try something like this and lmk how it goes?

```js
const REGISTRY = new WeakMap()

export default class InViewport extends Service {
  destroy() {
    REGISTRY = null;
  }
}
```

**Comment by allthesignals** [comment]
Hmm I can't seem to reproduce anymore. I don't understand why but the Chrome memory profiler sometimes produces inconsistent results across browser sessions. I'll give it another go later, but I'm spinning my wheels a little bit trying to do this, which in the past has been a sign that I am doing something differently and not realizing it.

**Comment by isao** [comment]
> Chrome memory profiler sometimes produces inconsistent results across browser sessions

Clicking the GC button (looks like a trash can) before taking the heap snapshot, will help reduce the chance of noise in the data.

**Comment by snewcomer** [comment]
👋 Is this still an issue?

**Comment by allthesignals** [comment]
I couldn't say—it's too hard to reproduce! Will close.
