### ISSUE TITLE
Cannot Use with Ember 3.11

### ISSUE THREAD

**Issue by jherdman** [DockYard/ember-in-viewport#204]
## Version

3.5.8

## Test Case

Install this addon in a new Ember 3.11 project, and have a classic component like this:

```javascript
export default Component.extend(InviewportMixin, {
  // etc
});
```

## Steps to reproduce

Boot up your test suite

## Expected Behavior

Ember runs

## Actual Behavior

Ember reports the following error:

```
Uncaught Error: Assertion Failed: You must call `this._super(...arguments);` when overriding `init` on a framework object. Please update <my-app@service:-observer-admin::ember1455> to call `this._super(...arguments);` from `init`
```

It took a little head scratching, but it seems that there's some kind of mismatch between the use of native classes in this addon, and classic ember components. The resolution was to refactor to native classes in the host app. This, however, is a bit surprising, and seems to suggest a breaking change.

EDIT: This is breaking addons that have components that use this mixin too.

**Comment by snewcomer** [comment]
Hey @jherdman!  Yeah in the case you are showing, we have a mix of framework objects that `extend()` (the mixin) and native classes (the service). You are right it does suggest a breaking change.  I think it might be worthwhile to try and see if refactoring the mixin to a native class helps.

**Comment by jherdman** [comment]
Is there any particular reason that the mixin couldn't simply be a component subclass that consumers of this lib subclass in turn? As it is it feels a little awkward to use:

```javascript
export default MyComponent extends Component.extend(TheMixin) {
  // blah
}
```

**Comment by snewcomer** [comment]
Ah you might have another dependency that is clobbering the 3.5.8 version.  observer-admin is not a service anymore.  Can you check with [ember-cli-dependency-lint](https://github.com/salsify/ember-cli-dependency-lint)?

**Comment by jherdman** [comment]
You are indeed correct. Resolving this fixed the root problem.
