### ISSUE TITLE
Modifier without mixin

### ISSUE THREAD

**Issue by mehulkar** [DockYard/ember-in-viewport#205]
I'd like to be able to use the underlying goodness of this addon in Octane mode using a modifier:

```hbs
<div {{did-enter-viewport this.myCallback}}></div>
```

This would let me move my component to a native class component / glimmer components without mixins. I could also put `myCallback` in an Ember helper, and avoid a JS context for my component entirely.

**Comment by buschtoens** [comment]
Very much in favor of your suggestion, @mehulkar! ❤️ 

And yes, as shown [somewhere hidden in the original RFC](https://github.com/emberjs/rfcs/blob/master/text/0373-Element-Modifier-Managers.md#determining-which-modifier-manager-to-use), the `owner` is passed to the modifier manager when it's instantiated, meaning we can use it to look up the service.

**Comment by buschtoens** [comment]
One issue I found while spiking out an implementation is that `watchElement` accepts `configOptions`:

> Options as the second argument to `inViewport.watchElement` include `intersectionThreshold`, `scrollableArea`, `viewportSpy` && `viewportTolerance`.

I'd add these as named args to the modifiers, like so:

```hbs
<div
  {{did-enter-viewport this.didEnterViewport viewportTolerance=100}}
>
</div>
```

This is an issue, when you want to use both modifiers at the same time and _may_ want to have different configs:

```hbs
<div
  {{did-enter-viewport this.didEnterViewport viewportTolerance=100}}
  {{did-exit-viewport  this.didExitViewport  viewportTolerance=50}}
>
</div>
```

I did not deep dive into the source code yet, but maybe someone already knows whether we could support this, with a slight refactor maybe?

**Comment by snewcomer** [comment]
@buschtoens Great!  Yeah the config options need to be the same since the IntersectionObserver's `callback` is involved based on the common config setup - `let observer = new IntersectionObserver(callback, configOptions);` <--- whether it is entering or exiting the viewport.

**Comment by buschtoens** [comment]
I think the cleanest solution then would be a joint `{{in-viewport}}` modifier:

```hbs
<div
  {{in-viewport
    enter=this.didEnterViewport
    exit=this.didExitViewport
    viewportTolerance=100
  }}
></div>
```

For convenience we may still add the `{{did-enter-viewport}}` and `{{did-exit-viewport}}`, but make them mutually exclusive, throwing an assertion that prompts the user to switch to `{{in-viewport}}`.

What do you think?

**Comment by snewcomer** [comment]
Less complicated is better 👍 I like it so far.  

Also, one thing to bring up is the act of `watchElement` for certain scenarios isn't standard necessarily.  For example, I might need to wait a tick to actually start watching the element in question (b/c say it is a content heavy page and the page doesn't have height yet).  Likely I wouldn't be able to use it for the examples I have.  Not necessarily needs to be taken into consideration for this modifier, but thought I would bring that up in case you come across solution in your exploration.

**Comment by buschtoens** [comment]
> One issue I found while spiking out an implementation is that `watchElement` accepts `configOptions`:
> 
> > Options as the second argument to `inViewport.watchElement` include `intersectionThreshold`, `scrollableArea`, `viewportSpy` && `viewportTolerance`.
> 
> I'd add these as named args to the modifiers, like so:
> 
> ```
> <div
>   {{did-enter-viewport this.didEnterViewport viewportTolerance=100}}
> >
> </div>
> ```
> 
> This is an issue, when you want to use both modifiers at the same time and _may_ want to have different configs:
> 
> ```
> <div
>   {{did-enter-viewport this.didEnterViewport viewportTolerance=100}}
>   {{did-exit-viewport  this.didExitViewport  viewportTolerance=50}}
> >
> </div>
> ```
> 
> I did not deep dive into the source code yet, but maybe someone already knows whether we could support this, with a slight refactor maybe?

[This assertion](https://github.com/DockYard/ember-in-viewport/pull/208/files#diff-e66ae1f3416fddfe8b153d7f3ce20bdfR51-R55) checks that you only ever use on modifier on a given element.
