### ISSUE TITLE
Debugging potential leaks

### ISSUE THREAD

**Issue by dbashford** [DockYard/ember-in-viewport#216]
I'm debugging some leak issues we have using ember-in-viewport. While I haven't got to the source just yet, I did notice this...

In the `in-viewport` service, you have a `startIntersectionObserver` function which instantiates an `ObserverAdmin` ([code](https://github.com/DockYard/ember-in-viewport/blob/master/addon/services/in-viewport.js#L40-L42)).

```js
startIntersectionObserver() {
  this.observerAdmin = new ObserverAdmin();
}
```

In the `in-viewport` service's `watchElement` function ([code](https://github.com/DockYard/ember-in-viewport/blob/master/addon/services/in-viewport.js#L58-L62)), you protect the creation of `observerAdmin`, making sure you don't create if you already have one.

```js
watchElement(element, configOptions = {}, enterCallback, exitCallback) {
  if (get(this, 'viewportUseIntersectionObserver')) {
    if (!get(this, 'observerAdmin')) {
      this.startIntersectionObserver();
    }
    ...
```

However, in the `_setInitialViewport` function of the `in-viewport` mixin ([code](https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L116-L125)) you call `startIntersectionObserver` without such a protection. 

```js
  _setInitialViewport(element) {
    const isTearingDown = this.isDestroyed || this.isDestroying;
    if (!element || isTearingDown) {
      return;
    }

    const inViewport = get(this, 'inViewport');

    if (get(this, 'viewportUseIntersectionObserver')) {
      inViewport.startIntersectionObserver();
      ...
```

I'm not positive that this is the cause of our leaks, but the loss/overwrite of the observer admin reference, which holds the registry that IS our leak, is making it hard to make any sort of fix.

Assuming this is the problem I think it might be, the right solution here might be to protect creation of `observerAdmin` inside `startIntersectionObserver` rather than its callers. I've made that locally while I debug things.

Happy to PR that in, but to be honest, I've been debugging a straight line to the leak and I've ignored some of what I've debugged through, so I may be missing a reason for re-creation of the `observerAdmin`

**Comment by snewcomer** [comment]
@dbashford 👋  I believe you are right!  We may need to remove this line.  What do you think?

https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L125

Also, for future reference, the `Mixin` will surely be deprecated in the future.  The `service` is the recommended path forward just in case I haven't stated it in the README.
