### ISSUE TITLE
onExit doesn't get fired on IE

### ISSUE THREAD

**Issue by AliceMakk** [DockYard/ember-in-viewport#230]
The library works perfect on Edge, but works half on IE 11
The event _onEnter_ gets fired, but the event _onExit_ doesn't.

## Version
3.7.1

## Test Case
```
const { onEnter, onExit } = this.inViewport.watchElement(e, { isIntersecting : true, intersectionThreshold : 0.5 });
onEnter(this.didEnterViewport.bind(this));
onExit(this.didExitViewport.bind(this));
```

Am I missing something please?

**Comment by snewcomer** [comment]
@AliceMakk 👋 Try `viewportSpy: true` in your configuration and lmk if that fixes it for you!

https://github.com/DockYard/ember-in-viewport#configuration

**Comment by AliceMakk** [comment]
Hi @snewcomer thank you for your quick reply. Yep, that fixed the problem, I'm just wondering about precautions said in the docs:

> When true, the library will continually watch the Component and re-fire hooks whenever it enters or leaves the viewport. Because this is expensive, this behaviour is opt-in. 

Just wondering why the onEnter event works and the onExit doesn't.

**Comment by snewcomer** [comment]
I updated the readme with the linked commit!  Thanks for reporting.  Hopefully helps others in the future!
