### ISSUE TITLE
TypeError: Cannot read property 'viewportConfig' of undefined

### ISSUE THREAD

**Issue by fran-worley** [DockYard/ember-in-viewport#232]
I suspect this is an issue caused by how we use `ember-in-viewport `in `ember-light-table` but @snewcomer any ideas why I'm suddenly getting this error for ember 3.4?

https://travis-ci.org/github/offirgolan/ember-light-table/jobs/671943228#L1453

I've tried dropping `ember-in-viewport` back down to 3.5.8 (which used to work) and it makes no difference. Any chance you could point me in the right direction?

**Comment by Gorzas** [comment]
The problem you're facing is in [this line](https://github.com/DockYard/ember-in-viewport/blob/master/addon/initializers/viewport-config.js#L33). I still don't know why does it fails with ember-light-table.

**Comment by fran-worley** [comment]
In the interests of progress, we're removing support for Ember 3.4 from the final release of Version 2.x.

**Comment by snewcomer** [comment]
@fran-worley Can this issue be closed?  It may have been lack of support for older versions...

**Comment by fran-worley** [comment]
I think so - we just had to drop support for ember <3.6
