### ISSUE TITLE
Use {{in-viewport}} modifier multiple times on a page only trigger the last one's callback

### ISSUE THREAD

**Issue by oo6** [DockYard/ember-in-viewport#245]
## Version
3.7.7

## Test Case
https://ember-twiddle.com/85422a05c7149e37a3871be3d75a47a9?openFiles=templates.application%5C.hbs%2C

## Steps to reproduce
Use `{{in-viewport}}` modifier multiple times on a page.

## Expected Behavior
Every modifier's `onEnter` will trigger.

## Actual Behavior
Only trigger the last one.

**Comment by MrChocolatine** [comment]
I can also reproduce the issue.
Updating to `3.7.7` suddenly breaks one of my test, a `onEnter` callback being not triggered.

**Comment by snewcomer** [comment]
`3.7.8`!  Thanks for reporting
