### ISSUE TITLE
onEvent(callback) API doesn't work

### ISSUE THREAD

**Issue by MaxKrai** [DockYard/ember-in-viewport#254]
## Description
If we use the onEnter() API from **Usage** [example](https://github.com/DockYard/ember-in-viewport#usage) callbacks will not be fired in browsers where IntersectionObserver is not supported (e.g. IE):
```
const { onEnter } = this.inViewport.watchElement(element);
onEnter(this.didEnterViewport.bind(this));
```
Appearance of element in viewport leads to idle calling of `noop()` [here](https://github.com/DockYard/ember-in-viewport/blob/d619d89b7b39deb598ce7fb4004252e5b6c7858c/addon/-private/raf-admin.js#L144)

## Workaround
Use modifier or pass callback to `watchElement`:
```
this.inViewport.watchElement(element, {}, this.didEnterViewport.bind(this));
```

**Comment by snewcomer** [comment]
@MaxKrai 👋 Thx for the issue.  I converted some of our dummy app examples to use this and the tests/ember serve seem to work correctly.  Possible to identify what is different than our examples?
