### ISSUE TITLE
viewportSpy: false triggering onEnter  everytime

### ISSUE THREAD

**Issue by sairam1610** [DockYard/ember-in-viewport#256]
## Version
v3.8.0

## Steps to reproduce
inject inViewPort service onEnter fired on each entry of element in the view port works fine with when used with mixin

```export default class MyClass extends Component {
  @service inViewport

  @action
  setupViewport() {
    const loader = document.getElementById('loader');
    const { onEnter } = this.inViewport.watchElement(loader);
    onEnter(this.didEnterViewport.bind(this));
  }

  didEnterViewport() {
    console.log("view port Entered")
  }

  willDestroyElement() {
    const loader = document.getElementById('loader');
    this.inViewport.stopWatching(loader);
  }
}
```
Is there anything wrong with this implementation ?
## Expected Behavior
should be fired once by default

## Actual Behavior
In my-class component `didEnterViewport()` function fired on every entry of loader in view port.

**Comment by sairam1610** [comment]
@snewcomer

**Comment by snewcomer** [comment]
@sairam1610 Do all your loaders have the same `id`?  If so, that hopefully is the issue (and not allowed according to the spec)!

If each loader does have different `ids`, do you have a minimal example I can look at?  We have a bunch of examples in the dummy app and tested quite well.

ember-in-viewport/tests/dummy/app/components/

**Comment by sairam1610** [comment]
I have tested in my-class component in infinity.hbs
`infinity.hbs`
```<div class="class-components">
  <div class="left">
    <ul>
      {{#each models as |val|}}
        <div class="infinity-class-item">
          <svg width="200" height="250" version="1.1" xmlns="http://www.w3.org/2000/svg">
            {{{val}}}
          </svg>
        </div>
      {{/each}}
    </ul>

    <MyClass @infinityLoad={{this.infinityLoad}} />
  </div>
</div>
```
`component.js`
```
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { inject as service } from '@ember/service';

export default class MyClass extends Component {
  @service inViewport

  @action
  setupViewport() {
    const loader = document.getElementById('loader');
    const { onEnter } = this.inViewport.watchElement(loader, { viewportSpy: false });
    onEnter(this.didEnterViewport.bind(this));
  }

  didEnterViewport() {
    console.log("view port entered")
  }

  willDestroyElement() {
    const loader = document.getElementById('loader');
    this.inViewport.stopWatching(loader);
  }
}
```

`my-class.hbs`
```
<div {{did-insert this.setupViewport}} id="loader" style="background-color: brown;">
    Hello there from loader
</div>

```

**Comment by snewcomer** [comment]
@sairam1610 I think I would need an example to test with up on github or twiddle that I can manually test to see what is wrong.  If you don't mind.

**Comment by pragatheeswarans** [comment]
@snewcomer I am using the `{{in-viewport}}` modifier and I couldn't figure out a way to call the `onEnter` listener only once. I tried passing `viewportSpy=false` to the modifier (even the default value should be false), the event seems to be firing every time when the element enters the viewport. 

Is there an option to execute the `onEnter` event once and then remove the event listener for the element when using the `{{in-viewport}}` modifier?

Here is a twiddle for reference.
https://ember-twiddle.com/c318b2c50578bd588f399a09ebd61cb2?openFiles=templates.application%5C.hbs%2C
