### ISSUE TITLE
Early bail out

### ISSUE THREAD

**Issue by fsmanuel** [DockYard/ember-in-viewport#26]
@poteto is there a easy way to prevent the mixin from beeing initialized? Lets say i set `viewportEntered = true` and `_setupElement` would bail out immediately. That would be great for `ember-lazy-image` when the image is already in cache and would save a lot of performance.

**Comment by poteto** [comment]
Hey @fsmanuel, yup that can definitely be done. Sorry I got back to you so late! Would you like to submit a PR for this? :)

**Comment by kellyselden** [comment]
Solved by #87.
