### ISSUE TITLE
Depreciation warnings

### ISSUE THREAD

**Issue by amokan** [dockyard/ember-in-viewport#29]
Not sure why I cannot pinpoint the issue, but I'm getting a bunch of depreciation warnings for the now retired `didScrollUp` (and other directions) even though I do not have these implemented in my code anyplace.

I get the same warnings on your demo app on divshot as well.

**Comment by poteto** [comment]
That's strange, it shouldn't be happening...

![screenshot 2015-06-06 15 16 33](https://cloud.githubusercontent.com/assets/1390709/8021055/55068126-0c5f-11e5-8988-55047b0396af.png)

**Comment by rwjblue** [comment]
@poteto - Likely unrelated, but the demo is deployed with production build so deprecations would have been stripped.

**Comment by amokan** [comment]
thank you @poteto
