### ISSUE TITLE
didExitViewport not fire

### ISSUE THREAD

**Issue by deivinsontejeda** [dockyard/ember-in-viewport#33]
Hi guys,

I wonder what would be the reason why `didExitViewport` is not fire?

**Comment by deivinsontejeda** [comment]
I will close this issue due to we have found the error and it was with [nanoScroller](https://jamesflorentino.github.io/nanoScrollerJS/) we will figure out how could work both.

**Comment by trumb1mj** [comment]
I'm actually running into this as well.  Were there any other package conflicts associated with this?  didEnterViewport is firing without issue.

**Comment by richpwf** [comment]
Same issue here :(

**Comment by poteto** [comment]
Do you have viewportSpy enabled?

**Comment by richpwf** [comment]
Doh! I'm an eejit! Thanks Lauren

On Apr 27, 2016, at 4:05 PM, Lauren Tan <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have viewportSpy enabled?
