### ISSUE TITLE
didEnterViewport should also trigger from the bottom rather than only from the top.

### ISSUE THREAD

**Issue by carloscheddar** [DockYard/ember-in-viewport#40]
Currently when scrolling the hooks trigger when the `top` of the element is in view. It would be nice if we could set a flag to be able to trigger from the bottom even if the top is not in view yet.

**Comment by snewcomer** [comment]
@carloscheddar This uses IntersectionObserver now.  Lmk if this is still a problem.

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by adong** [comment]
I think its overlooked a condition that:

Parent element is `display: none`, while children is `display: block` or whatever.

Maybe add another check like

```
$('#ember1745')[0].offsetHeight > 0
```

```
    _setViewportEntered: function _setViewportEntered() {
      var context = arguments.length <= 0 || arguments[0] === undefined ? null : arguments[0];

      assert('You must pass a valid context to _setViewportEntered', context);

      var element = get(this, 'element');

      if (!element) {
        return;
      }

      var $contextEl = $(context);
      /// add some addition check for `display: none` here?
      var boundingClientRect = element.getBoundingClientRect();

      this._triggerDidAccessViewport((0, _emberInViewportUtilsIsInViewport['default'])(boundingClientRect, $contextEl.innerHeight(), $contextEl.innerWidth(), get(this, 'viewportTolerance')));

      if (boundingClientRect && get(this, 'viewportUseRAF')) {
        rAFIDS[get(this, 'elementId')] = window.requestAnimationFrame(bind(this, this._setViewportEntered, context));
      }
    },
```


Just a thought

See reference: 
1. https://davidwalsh.name/offsetheight-visibility
2. https://stackoverflow.com/questions/15924751/check-if-a-element-is-displaynone-or-block-on-click-jquery
