### ISSUE TITLE
Error in _unbindListeners in component integration tests

### ISSUE THREAD

**Issue by jkeen** [DockYard/ember-in-viewport#45]
After mixing this into a component, integration tests keep throwing `Uncaught TypeError: Cannot read property 'forEach' of undefined`. This is on Ember 2.2.

It's failing when it's finding that `viewportListeners` hasn't been set. 

Is there something I need to do to my test to get this to work like it should? Otherwise, what's the best way to test a component with this mixed in?

**Comment by jkeen** [comment]
You can work around this by defining a `viewportListeners: []` property on the component, but that doesn't feel right.

**Comment by swalkinshaw** [comment]
Just wanted to report I also ran into the same issue and defining `viewportListeners: []` worked.

**Comment by poteto** [comment]
The above solution is OK in my book. Testing the "in viewport" behavior is very difficult / non-trivial and I would avoid doing so in your integration test.

**Comment by swalkinshaw** [comment]
@poteto just to clarify, the error occurs when simply rendering a component in an integration test. I personally don't have an issue with just defining `viewportListeners` though since, in my case, I was overriding them so it kind of makes sense.

```js
import Ember from 'ember';
import InViewportMixin from 'ember-in-viewport';

export default Ember.Component.extend(InViewportMixin, {
  viewportListeners: [],
  viewportOptionsOverride: on('didInsertElement', function() {
    this.setProperties({
      viewportSpy: true,
      viewportListeners: [
        { context: window, event: 'scroll.scrollable' },
        { context: window, event: 'resize.resizable' },
        { context: document, event: 'touchmove.scrollable' }
      ]
    });
  })
});
```

**Comment by poteto** [comment]
Yeah, it fails because the initializer isn't invoked in the integration test. I can add a guard to the mixin in case it is undefined

**Comment by elidupuis** [comment]
Just ran into this issue myself and made a quick PR (#52).

**Comment by sethbrasile** [comment]
Ran into this issue, it was blowing up my mocha tests with `undefined is not an object (evaluating 'this.cache.subject')` and `Assertion Failed: You cannot use the same root element (#ember-testing) multiple times in an Ember.Application`

Not sure how it's related, but making @elidupuis' change fixes it.

**Comment by danielleadams** [comment]
It looks like it's probably the same error because the first one is trying to access the undefined properties (which are set in `init`). The second is simply because your tests weren't tearing down the setup of the previous test properly due to the initial error.

I had similar behavior and had to created a `Mixin` inside the application that extended the addon.

**Comment by sethbrasile** [comment]
ahhh @danielleadams I hadn't put enough thought into it. I *should* know to always look at the first error when there are two, but the 2nd seemed more prevalent so I was stupidly focusing on that one. Thanks! Maybe next time it won't take me 2 hours to figure out :D 

To anyone ending up here from the google, I just added `viewportListeners: []` to the component that is using the mixin.
