### ISSUE TITLE
Breaking change from 2.x which EnumerableUtils is removed, using lodash instead.

### ISSUE THREAD

**Issue by systembugtj** [dockyard/ember-in-viewport#47]
http://emberjs.com/blog/2015/05/24/another-two-oh-status-update.html

The ArrayPolyfills and EnumerableUtils libraries are being pulled out into a library; most apps should prefer lodash or other utility libs.

**Comment by rwjblue** [comment]
This was fixed in https://github.com/dockyard/ember-in-viewport/pull/32 and has already been released.  Please update to the latest version.
