### ISSUE TITLE
Deprecations in Ember 2.3.0

### ISSUE THREAD

**Issue by Alinaki** [DockYard/ember-in-viewport#57]
```
DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object.
```

Official documentation recommends to use ember-getowner-polyfill

http://emberjs.com/deprecations/v2.x/#toc_injected-container-access

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/DockYard/ember-in-viewport/pull/56
