### ISSUE TITLE
Only called first time

### ISSUE THREAD

**Issue by erichonkanen** [DockYard/ember-in-viewport#61]
Hello, I have a `paginate-loader` component that is using this mixin for infinite scroll, however it seems to only be called the first time it enters the viewport...

Here is my paginate-loader component...
```
import Ember from 'ember'
import InViewportMixin from 'ember-in-viewport'

PaginateLoaderComponent = Ember.Component.extend InViewportMixin,
  didEnterViewport: ->
    log 'entered'
    # Call the 'loadMore' action that is passed into the component.
    @sendAction 'loadMore'

export default PaginateLoaderComponent
```

in my templates/route.hbs
```
          {{#each stores as |store|}}}
          ...
          {{/each}}
          {{#paginate-loader loadMore=(route-action 'loadMore')}}
          loading...
          {{/paginate-loader}}
```

So when I scroll down and the paginate-loader comes into view the first time, it loads more data and it goes out of view... however scrolling down further until it comes into view again does NOT trigger the `didEnterViewport` function again... Why is this? How can I have it called every time?

**Comment by poteto** [comment]
Either set `viewportSpy` to `true` in your `config/environment` or set it on the component itself:

```js
module.exports = function(environment) {
  var ENV = {
    viewportConfig: {
      viewportSpy: true
    }
  };
};
```

**Comment by erichonkanen** [comment]
doh missed the setting for spying... do I need to unbind everything on route change or is that handled automatically if I set the spy to true?

**Comment by poteto** [comment]
It will unbind it for you when the component's element is destroyed.

**Comment by erichonkanen** [comment]
thanks!
