### ISSUE TITLE
partial viewport support

### ISSUE THREAD

**Issue by davidpett** [DockYard/ember-in-viewport#67]
I forked and added some functionality to allow for partial viewport (i.e. only the top tolerance matches) https://github.com/davidpett/ember-in-viewport/blob/partial-viewport/addon/utils/is-in-viewport.js However this fails the test https://github.com/davidpett/ember-in-viewport/blob/master/tests/unit/utils/is-in-viewport-test.js#L53 because it will never fire when not in viewport. Any thoughts?

**Comment by snewcomer** [comment]
This has been fixed with the possibility to define a scrollable area!  Lmk if that wasn't what you were trying to fix. 

https://github.com/DockYard/ember-in-viewport#advanced-usage-options
