### ISSUE TITLE
Rehost demo app

### ISSUE THREAD

**Issue by SaladFork** [DockYard/ember-in-viewport#68]
The demo app is no longer available since divshot went offline.

> **Site Unavailable**
> 
> Divshot, the hosting provider for this website, has ceased operation as of December 22, 2015 ... If this is your website, please update your DNS to point to a new hosting provider!

http://development.ember-in-viewport-demo.divshot.io/

**Comment by snewcomer** [comment]
Closing for now.  The dummy app has some good examples.  It is a good idea though, esp for new ppl. But not sure anybody has the time here to get it up and running.
