### ISSUE TITLE
viewportEntered & viewportExited as "real" hooks

### ISSUE THREAD

**Issue by rwjblue** [dockyard/ember-in-viewport#7]
The README uses the term "hook" to refer to boolean values that are set on the root of the component. IMHO, these are "flags" (or something) but a hook would be a function that is invoked.

I would like to have functions that are called instead of forcing observation to consume the mixin. This would make it simpler to do complicated logic on entering/exiting the viewport without relying on using an observer.

We could use the following as a default implementation:

```javascript
viewportEntered() {
  set(this, 'hasEnteredViewport', true);
  this.trigger('viewportEntered'); // send the `viewportEntered` event
}
```

---

Background: I am looking to swap ember-waypoints over to use ember-in-viewport instead of wrapping the jQuery plugin, and I would like to avoid having to use observation for triggering an action.

**Comment by rwjblue** [comment]
The proposed change would be a breaking change, so we could change the names of the functions to avoid that breakage if you prefer...

**Comment by poteto** [comment]
Working on it!
