### ISSUE TITLE
Only detecting when elements are above or below viewport

### ISSUE THREAD

**Issue by alexlafroscia** [DockYard/ember-in-viewport#70]
Is there some way to configure this to only detect when the element is above or below the viewport?  I don't care if it went off the page sideways and only want to check if it scrolled off the top.

I was able to achieve the effect by setting `viewportTolerance.left` and `viewportTolerance.right` to a really large, arbitrary number, but a way to disable the left-right check altogether would be even better since I figure there are some computations that could then be avoided.

**Comment by tomdale** [comment]
Could you just use `Infinity` as the value? I suspect doing an integer comparison is actually faster than having two different code paths from treating it as a separate case.
