### ISSUE TITLE
Setting viewportOverrides with Ember.on doesn't work as expected

### ISSUE THREAD

**Issue by blimmer** [DockYard/ember-in-viewport#72]
In the readme, it is recommended to override options like this:

``` js
export default Ember.Component.extend(InViewportMixin, {
  viewportOptionsOverride: Ember.on('didInsertElement', function() {
    Ember.setProperties(this, {
      viewportUseRAF            : true,
      viewportSpy               : false,
      viewportScrollSensitivity : 1,
      viewportRefreshRate       : 150,
      viewportTolerance: {
        top    : 50,
        bottom : 50,
        left   : 20,
        right  : 20
      }
    });
  })
});
```

However, I noticed that setting viewportSpy wasn't working for me. AFAIK, when `Ember.on` runs is actually non-deterministic. Since we're setting up the observer in the `didInsertElement` hook in the addon, I actually think it's more appropriate to override like this:

``` js
export default Ember.Component.extend(InViewportMixin, {
  didInsertElement() {
    Ember.setProperties(this, {
      viewportUseRAF            : true,
      viewportSpy               : false,
      viewportScrollSensitivity : 1,
      viewportRefreshRate       : 150,
      viewportTolerance: {
        top    : 50,
        bottom : 50,
        left   : 20,
        right  : 20
      }

      this._super(...arguments);
    });
  })
});
```

to ensure that the properties are set before the `InViewportMixin` runs. 

Does that sound correct? I'll happily submit a PR updating the docs if this sounds reasonable.

**Comment by poteto** [comment]
Hey @blimmer, thanks for opening this issue. Your override is most definitely correct, although I would move the `super` call to come before the `setProperties`. A PR would be welcome!

**Comment by blimmer** [comment]
@poteto I actually think it's important to call `_super` after setting the properties because `_super` will call the mixin's didInsertElement before you set the properties. Check it out:

```javascript
export default Ember.Component.extend(InViewportMixin, {
  didInsertElement() {
    this._super(...arguments);

    console.log('*** IN COMPONENT MIXIN didInsertElement');
  }
});
```

and the console output:
```bash
in-viewport.js:42*** IN IN_VIEWPORT MIXIN didInsertElement
foo-bar.js:6*** IN COMPONENT MIXIN didInsertElement
```

**Comment by blimmer** [comment]
Actually, why do we overwrite the options in the `init` [method](https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L29-L33) anyway?

In my use case, I just want to set the `viewportSpy` method and it seems weird that it gets overwritten on `init`. Seems like I should be able to do:

```javascript
export default Ember.Component.extend(InViewportMixin, {
  viewportSpy: true,
});
```

What's the reason for overwriting in `init` and requiring the user to tap into `didInsertElement`?

**Comment by snewcomer** [comment]
Closing since the mixin approach is less and less common
