### ISSUE TITLE
Fastboot errors

### ISSUE THREAD

**Issue by rwwagner90** [DockYard/ember-in-viewport#76]
`document is not defined`

Caused by 

```js
viewportListeners: [{ context: window, event: 'scroll.scrollable' }, { context: window, event: 'resize.resizable' }, { context: document, event: 'touchmove.scrollable' }],
```

**Comment by poteto** [comment]
That was removed a while ago, what version are you using?

**Comment by rwwagner90** [comment]
It's possible I was pointing to an old version. I haven't run into this lately, so I will close, and open again if I see it again.
