### ISSUE TITLE
Falls at 2nd hurdle - (1) installed (2) doesn't get recognised

### ISSUE THREAD

**Issue by rmcsharry** [DockYard/ember-in-viewport#93]
Seems like a great add-on, but in Ember 2.7 it cannot be found...?

component/trail-card.js
```
import Ember from 'ember';
import InViewportMixin from 'ember-in-viewport';

export default Ember.Component.extend(InViewportMixin, {
  didEnterViewport() {
    console.log('entered');
  },
});
```

Error in console:

228 Uncaught Error: Could not find module `ember-in-viewport` imported from `trekclient/components/trail-card`

**Comment by martndemus** [comment]
Just to be sure: Have you restarted the development server?

**Comment by rmcsharry** [comment]
Thanks...note to self: never stay up all night coding.
