### ISSUE TITLE
Need to coearse bounding client rect values to integers

### ISSUE THREAD

**Issue by les2** [DockYard/ember-in-viewport#96]
I originally reported this issue against ember-light-table here: https://github.com/offirgolan/ember-light-table/issues/199

This comment has all the relevant details: https://github.com/offirgolan/ember-light-table/issues/199#issuecomment-264662429

For your convenience, I'm copying that text below:

TL;DR -- this is a floating point bug ... in ember-in-viewport addon.

This is really hard to reproduce because you need the numbers to round just right.

# Details

The bug is in one of these two locations:
- https://github.com/DockYard/ember-in-viewport/blob/master/addon/mixins/in-viewport.js#L94-L104
- https://github.com/DockYard/ember-in-viewport/blob/master/addon/utils/is-in-viewport.js#L12-L27

Example.

```
// values for bounding client rect of the `lt-infinity` element!
top:  318.85418701171875 left:  0 bottom:  318.85418701171875 right:  1451.1112060546875

// tolerance values:
topTolerance:  0
leftTolerance:  0
bottomTolerance:  500
rightTolerance:  0

// width and height of the window (viewport):
width:  1451 height:  820

// ALL of these have to be TRUE in order for the lt-infinity element to be *in* the viewport:
(top + topTolerance)       >= 0                   ? true
(left + leftTolerance)     >= 0                     ? true
(bottom - bottomTolerance) <= height    ? true
(right - rightTolerance)   <= width           ? FALSE     <---- this is the problem!
```

right boundary check in detail:
```
(right - rightTolerance)   <= width
1451.1112060546875 <= 1451    ===> FALSE
```

So we need to round (down) to integer value the bounding client rect values, I guess.

I'm going to look at a PR to the ember-in-viewport repo in a little bit and then open a PR to this repo that just bumps the version of that package.

## Version
2.1.0

## Test Case
Reproduced it with an ember-light-table based example described in this comment: https://github.com/offirgolan/ember-light-table/issues/199#issuecomment-264664966

- Go to https://les2.github.io/ember-light-table-zoom-bug/#/elt-demo
- Set your zoom to 90%
- Refresh --- notice no data will be loaded

I'm going to work on a PR to fix this in the next couple of days. I'm on paternity leave so please be patient with me!

**Comment by les2** [comment]
CC @offirgolan @buschtoens

**Comment by les2** [comment]
Updated description with instructions for reproducing the problem.

**Comment by offirgolan** [comment]
@les2 thanks for taking this on. I was able to reproduce this on my machine as well via your demo site + instructions. I look forward for your PR!

**Comment by buschtoens** [comment]
Fantastic detective work! :mag:

**Comment by poteto** [comment]
Great job! Happy to accept the PR once it's ready
